In [3]:

import numpy as np
 
data = [ ]
 
for one in range(1, 4):
	twod = [ ]
	
	for two in range(1, 4):
		twod.append([one, two])
	
	data.append(twod)
 
ar = np.array(data)
 
print(ar)

[[[1 1]
  [1 2]
  [1 3]]

 [[2 1]
  [2 2]
  [2 3]]

 [[3 1]
  [3 2]
  [3 3]]]


In [ ]:
import pandas as pan
df = pan.DataFrame({'C1':[ 3, 6, 2],
                       'C2':[ 0, 5, 1],
                       'C3':[ 7, 9, 3]},
                     index = [ 1, 2, 3])
print(df.values[1, 2])

In [91]:
import numpy as np
import pandas as pd
ar = np.array([['[1,1]','[1,2]','[1,3]'],
                ['[2,1]','[2,2]','[2,3]'],
                ['[3,1]','[3,2]','[3,3]']])
df = pd.DataFrame(data = ar, columns=['Combo1','Combo2','Combo3'], index=[1,2,3])



print(df)

Combo1 Combo2 Combo3
1  [1,1]  [1,2]  [1,3]
2  [2,1]  [2,2]  [2,3]
3  [3,1]  [3,2]  [3,3]